services:
  frontend:
    container_name: log4j-collector-frontend
    image: ghcr.io/bluestoneag/log4j-collector-frontend:latest
    environment:
      - API_URL=http://localhost:8080/api/v1/reports
    ports:
      - 80:80
