services:
  frontend:
    container_name: log4j-collector-frontend
    image: ghcr.io/bluestoneag/log4j-collector-frontend:latest
    build:
      context: .
      args:
        - API_ADDR=192.168.1.1
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - 80:80
